POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Eduardo",
    "email": "e@e.com",
    "password": "12345"
}

###

POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
    "email": "e@e.com",
    "password": "12345"
}